export enum AuthFailed {
  USER_NOT_FOUND = "AUTH/USER_NOT_FOUND",
  PASSWORD_MISMATCH = "AUTH/PASSWORD_MISMATCH",
  INVALID_TOKEN = "AUTH/INVALID_TOKEN",
  SESSION_NOT_FOUND = "AUTH/SESSION_NOT_FOUND",
  SESSION_FINISHED = "AUTH/SESSION_FINISHED",
  STRONG_SESSION_REQUIRED = "AUTH/STRONG_SESSION_REQUIRED",
  SESSION_EXPIRED = "AUTH/SESSION_EXPIRED"
}
